apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-extra-exporter
  labels:
    app: kube-extra-exporter
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kube-extra-exporter
  template:
    metadata:
      labels:
        app: kube-extra-exporter
    spec:
      containers:
      - image: tong16/kube-extra-exporter:v0.1.0
        imagePullPolicy: Always
        name: kube-extra-exporter
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /rootfs
          mountPropagation: HostToContainer
          name: rootfs
          readOnly: true
      hostPID: true
      serviceAccountName: kube-extra-exporter
      volumes:
      - hostPath:
          path: /
          type: ""
        name: rootfs
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/clusterstate: "true"
  labels:
    app: kube-extra-exporter
  name: kube-extra-exporter
  namespace: default
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kube-extra-exporter
  type: ClusterIP
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kube-extra-exporter
rules:
- apiGroups: [""]
  resources:
  - pods
  verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-extra-exporter
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kube-extra-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-extra-exporter
subjects:
- kind: ServiceAccount
  name: kube-extra-exporter
  namespace: default